services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: acore
      MYSQL_USER: acore
      MYSQL_PASSWORD: acore
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - 3306:3306

  valkey:
    image: docker.io/bitnami/valkey:8.0
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
    volumes:
      - 'valkey_data:/bitnami/valkey/data'

  redis-insight:
    image: redis/redisinsight:latest
    restart: always
    ports:
      - "5540:5540"
    volumes:
      - redis-insight:/data

    

  adminer:
    image: adminer
    ports:
      - 8081:8080
      

volumes:
  mysql-data:
  redis-insight:
  valkey_data:
    driver: local