#!/usr/bin/env bun
/**
 * gen_talent_rank_rules - regenerate the SoloQ "max out your learned talents"
 * table (`src/game/Arenacraft/soloq/TalentRanks.hpp`) from the client data.
 *
 * A talent can grant a single rank while the higher ranks of the same ability
 * are learned outside the talent tree (class trainer / vendor). Penance is the
 * canonical example: the talent teaches 47540, the trainer teaches up to 53007.
 * If a character knows the first rank but not the max rank it is missing free
 * power, so SoloQ refuses to queue it.
 *
 * The rule set is deliberately narrow and reviewable: only talents that grant
 * exactly one rank (`Talent.dbc` has a single non-zero RankID) and whose spell
 * chain (from `spell_ranks`) extends past that rank. Multi-rank talents are
 * skipped because a partial build (e.g. 3/5) is legitimate. The generated
 * header carries the ability name on every row so the list can be curated by
 * hand; delete rows you do not want to enforce.
 *
 * Usage: bun scripts/src/gen_talent_rank_rules.ts
 */
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { readDbc } from "./lib/dbc.ts";
import { repoRoot } from "./lib/repo.ts";

const OUTPUT = join(repoRoot, "src", "game", "Arenacraft", "soloq", "TalentRanks.hpp");

// Class trainer entries the gear vendor's "Learn Spells" serves (keep in sync
// with arenacraft::ClassTrainerEntry in src/game/Arenacraft/ClassTrainer.cpp).
// A rule is only kept when the max rank is sold by one of these, so every
// violation can be fixed at the vendor.
const CLASS_TRAINERS = [913, 927, 987, 917, 376, 28471, 986, 328, 461, 3033];

const talents = readDbc(join(repoRoot, "data", "dbc", "Talent.dbc"));
const spells = readDbc(join(repoRoot, "data", "dbc", "Spell.dbc"));

const spellName = new Map<number, string>();
for (const rec of spells.records) spellName.set(rec[0]!, spells.string(rec[136]!));

// Resolve the trainer spell lists: a negative SpellID references another
// trainer entry whose rows are inlined (same expansion the core does in
// ObjectMgr::LoadTrainerSpell).
const trainerSql = readFileSync(join(repoRoot, "data", "sql", "base", "db_world", "npc_trainer.sql"), "utf8");
const trainerDirect = new Map<number, Set<number>>();
const trainerRefs = new Map<number, Set<number>>();
for (const m of trainerSql.matchAll(/\(\s*(-?\d+)\s*,\s*(-?\d+)\s*,/g))
{
  const entry = Number(m[1]);
  const spell = Number(m[2]);
  if (entry < 0) continue;
  const target = spell > 0 ? trainerDirect : trainerRefs;
  const id = Math.abs(spell);
  if (!target.has(entry)) target.set(entry, new Set());
  target.get(entry)!.add(id);
}
const expandTrainer = (entry: number, seen = new Set<number>()): Set<number> =>
{
  const out = new Set<number>(trainerDirect.get(entry) ?? []);
  if (!seen.has(entry))
  {
    seen.add(entry);
    for (const ref of trainerRefs.get(entry) ?? []) for (const spell of expandTrainer(ref, seen)) out.add(spell);
  }
  return out;
};
const vendorSpells = new Set<number>();
for (const entry of CLASS_TRAINERS) for (const spell of expandTrainer(entry)) vendorSpells.add(spell);

// spell_ranks: (first_spell_id, spell_id, rank), ordered by first then rank.
const sql = readFileSync(join(repoRoot, "data", "sql", "base", "db_world", "spell_ranks.sql"), "utf8");
const chains = new Map<number, Array<{ spell: number; rank: number }>>();
for (const m of sql.matchAll(/\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*\)/g))
{
  const first = Number(m[1]);
  if (!chains.has(first)) chains.set(first, []);
  chains.get(first)!.push({ spell: Number(m[2]), rank: Number(m[3]) });
}
for (const chain of chains.values()) chain.sort((a, b) => a.rank - b.rank);

interface Rule
{
  talentId: number;
  first: number;
  max: number;
}

const rules: Rule[] = [];
for (const rec of talents.records)
{
  const talentId = rec[0]!;
  const rankIds = [rec[4]!, rec[5]!, rec[6]!, rec[7]!, rec[8]!].filter((x) => x !== 0);
  if (rankIds.length !== 1) continue; // partial multi-rank builds are legitimate
  if (rec[19]! !== 1) continue; // rank is only learned into the spellbook when flagged

  const first = rankIds[0]!;
  const chain = chains.get(first);
  if (!chain) continue;
  const max = chain[chain.length - 1]!.spell;
  if (max === first) continue;
  if (!vendorSpells.has(max)) continue; // must be fixable at the vendor

  rules.push({ talentId, first, max });
}
rules.sort((a, b) => a.first - b.first);

const name = (id: number) => (spellName.get(id) ?? "?").replace(/\s+/g, " ").trim();

// Pre-pad the trailing comments so clang-format leaves them as-is.
const rows = rules.map((r) => `    {${r.first}, ${r.max}},`);
const width = Math.max(...rows.map((r) => r.length));
const entries = rows.map((row, i) => `${row.padEnd(width)} // ${name(rules[i]!.first)}`).join("\n");

const header = `// Generated by scripts/src/gen_talent_rank_rules.ts - do not edit by hand
// except to curate (remove rows you do not want to enforce).
//
// Talent abilities whose rank 1 comes from the talent tree but whose max rank is
// learned elsewhere (class trainer / vendor). SoloQ refuses to queue a character
// that knows the first rank without the max rank. Keep this list conservative:
// only single-rank talents are included, so a multi-rank partial build is never
// flagged. Regenerate with:
//   bun scripts/src/gen_talent_rank_rules.ts
#pragma once

#include <array>
#include <cstdint>

namespace arenacraft::soloq
{
struct TalentRankRule
{
  uint32_t firstRank;
  uint32_t maxRank;
};

inline constexpr std::array<TalentRankRule, ${rules.length}> TalentRankRules = {{
${entries}
}};
} // namespace arenacraft::soloq
`;

writeFileSync(OUTPUT, header);
console.log(`wrote ${rules.length} rules to ${OUTPUT}`);
