// Generated by scripts/src/gen_talent_rank_rules.ts - do not edit by hand
// except to curate (remove rows you do not want to enforce).
//
// Talent abilities whose rank 1 comes from the talent tree but whose max rank is
// learned elsewhere (class trainer / vendor). SoloQ refuses to queue a character
// that knows the first rank without the max rank. Keep this list conservative:
// only single-rank talents are included, so a multi-rank partial build is never
// flagged. Regenerate with:
//   bun scripts/src/gen_talent_rank_rules.ts
#pragma once

#include <array>
#include <cstdint>

namespace arenacraft::soloq
{
struct TalentRankRule
{
  uint32_t firstRank;
  uint32_t maxRank;
};

inline constexpr std::array<TalentRankRule, 43> TalentRankRules = {{
    {724, 48087},   // Lightwell
    {974, 49284},   // Earth Shield
    {1329, 48666},  // Mutilate
    {3674, 63672},  // Black Arrow
    {5570, 48468},  // Insect Swarm
    {11113, 42945}, // Blast Wave
    {11366, 42891}, // Pyroblast
    {11426, 43039}, // Ice Barrier
    {12294, 47486}, // Mortal Strike
    {15407, 48156}, // Mind Flay
    {16511, 48660}, // Hemorrhage
    {17877, 47827}, // Shadowburn
    {18220, 59092}, // Dark Pact
    {19236, 48173}, // Desperate Prayer
    {19306, 48999}, // Counterattack
    {19386, 49012}, // Wyvern Sting
    {19434, 49050}, // Aimed Shot
    {20243, 47498}, // Devastate
    {20473, 48825}, // Holy Shock
    {20925, 48952}, // Holy Shield
    {30108, 47843}, // Unstable Affliction
    {30283, 47847}, // Shadowfury
    {30706, 57722}, // Totem of Wrath
    {31661, 42950}, // Dragon's Breath
    {31935, 48827}, // Avenger's Shield
    {34861, 48089}, // Circle of Healing
    {34914, 48160}, // Vampiric Touch
    {44425, 44781}, // Arcane Barrage
    {44457, 55360}, // Living Bomb
    {47540, 53007}, // Penance
    {48181, 59164}, // Haunt
    {48438, 53251}, // Wild Growth
    {48505, 53201}, // Starfall
    {49143, 55268}, // Frost Strike
    {49158, 51328}, // Corpse Explosion
    {49184, 51411}, // Howling Blast
    {50516, 61384}, // Typhoon
    {50796, 59172}, // Chaos Bolt
    {51490, 59159}, // Thunderstorm
    {53301, 60053}, // Explosive Shot
    {55050, 55262}, // Heart Strike
    {55090, 55271}, // Scourge Strike
    {61295, 61301}, // Riptide
}};
} // namespace arenacraft::soloq
