version: '3'

services:
  devcontainer:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached 
    command: sleep infinity

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_USER: acore
      MYSQL_PASSWORD: acore
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - 3306:3306
  
  adminer:
    image: adminer
    ports:
      - 8081:8080

volumes:
  mysql-data: