/*
 * This file is part of the AzerothCore Project. See AUTHORS file for Copyright information
 *
 * This program is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Affero General Public License as published by the
 * Free Software Foundation; either version 3 of the License, or (at your
 * option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for
 * more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program. If not, see <http://www.gnu.org/licenses/>.
 */

// This file was generated by the CMake build from ModulesLoader.cpp.in.cmake;
// in the zig build it is hand-maintained: keep it in sync with the module
// directories under src-port/modules.

#include "Define.h"
#include <string>
#include <vector>

#include "ModulesScriptLoader.h"

// Modules
void Addmod_arenacraftScripts();
void Addmod_duel_resetScripts();

/// Exposed in script modules to register all scripts to the ScriptMgr.
void AddModulesScripts()
{
    // Modules
    Addmod_arenacraftScripts();
    Addmod_duel_resetScripts();
}
