/*
 * This file is part of the AzerothCore Project. See AUTHORS file for Copyright information
 *
 * This program is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Affero General Public License as published by the
 * Free Software Foundation; either version 3 of the License, or (at your
 * option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for
 * more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program. If not, see <http://www.gnu.org/licenses/>.
 */

// This file was generated by the CMake build from ScriptLoader.cpp.in.cmake;
// in the zig build it is hand-maintained: keep it in sync with the script
// directories under src-port/scripts.

#include "Define.h"
#include <string>
#include <vector>

#include "ScriptLoader.h"

// Default scripts
void AddCommandsScripts();
void AddCustomScripts();
void AddEventsScripts();
void AddOutdoorPvPScripts();
void AddPetScripts();
void AddSpellsScripts();
void AddWorldScripts();

/// Exposed in script modules to register all scripts to the ScriptMgr.
void AddScripts()
{
    // Default scripts
    AddCommandsScripts();
    AddCustomScripts();
    AddEventsScripts();
    AddOutdoorPvPScripts();
    AddPetScripts();
    AddSpellsScripts();
    AddWorldScripts();
}
